### ISSUE TITLE
Armourstand dupe bug

### ISSUE THREAD

**Issue by thephoenixlodge** [BluSunrize/TravellersGear#12] opened 2014-12-29 00:38 UTC
I'm encountering a bit of an issue with mana tablets from botania interacting badly with the armourstand. When I have armour on the stand and open up the interface, one of the armour slots on the stand is outright replaced with a clone of the mana tablet in my inventory, deleting the piece of armour and resulting in a now duplicated mana tablet just sitting in a slot it can't even be put in normally.

**Comment by BluSunrize** [comment] 2015-01-02 11:11
After trying some versions of Botania between 141 and 148, I've determined that the bug starts with build 144. I have not been able to figure out the cause through the commits.
Maybe @Vazkii has an idea?

**Comment by Vazkii** [comment] 2015-01-02 14:24
I didn't really change anything regarding the tablet or mana handling code on 144. Not really sure what's happening here.

**Comment by BluSunrize** [comment] 2015-01-02 15:16
No idea either. Checked all my methods in the container, nothing indicated to be the source of the error.
I'll keep you posted but I don't know if I can find it.

**Comment by whitestarx0312** [comment] 2015-01-15 02:35
I can replicate this:

Putting a ring of magnetization inside the armor stand, then having another player take it out replicates it. I don't think I can replicate this by myself, but I can take some screenshots on my side if you need me to.

**Comment by BluSunrize** [comment] 2015-01-15 22:33
Should be fixed in the newest release of Traveller's Gear: 1.14

**Closed by BluSunrize** 2015-01-15 22:33 UTC
